# Generated by Django 2.2.1 on 2019-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=128, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('agender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2)),
                ('birth_date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '演员',
                'db_table': 't_actor',
            },
        ),
    ]
