# Generated by Django 2.2.1 on 2019-08-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default='', upload_to='actor/'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=30)),
                ('m_pub_date', models.DateField()),
                ('mread', models.PositiveIntegerField()),
                ('mcomment', models.TextField()),
                ('mimage', models.ImageField(upload_to='movies/')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuapp.Actor')),
            ],
            options={
                'verbose_name_plural': '电影',
            },
        ),
    ]
