# Generated by Django 2.2.1 on 2019-08-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0002_auto_20190802_1739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='t_movie',
        ),
    ]
